
development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ride_with_me_development
  pool: 5
  username: oculardexterity
  password:


test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: ride_with_me_test
  pool: 5
  username: oculardexterity
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ride_with_me
  pool: 5
  username: oculardexterity
  password:
